Utility startup details added
newrelic/nr-entity-tag-sync pull request #18
Opened 2023-11-24 17:22 UTC by nijugeorge173

# Description

Added details required for the proper functioning of the utility.

2023-12-06 20:42 UTC, sdewitt-newrelic requested changes
@nijugeorge173 sorry about that, though I had clicked submit review already but missed that step.  Please see requested changes.

2023-12-06 20:53 UTC, nijugeorge173 commented on README.md
> +4. Set the appropriate environment variables. Environment variable 'NEW_RELIC_LICENSE_KEY' is mandatory.
It gave a error on InterOp stating that license key needs to be of length 40 and the utility did not run.

2023-12-06 21:09 UTC, nijugeorge173 commented on README.md
> +4. Set the appropriate environment variables. Environment variable 'NEW_RELIC_LICENSE_KEY' is mandatory.
Added the PR description

2023-12-06 21:10 UTC, nijugeorge173 commented on README.md
> +   [the sample configuration file](configs/config.sample.yml).Place the configuration file inside 'configs' folder created at same location at CMDB utility executable
Pushed

2023-12-14 20:48 UTC, jbeveland27 approved these changes

2023-12-14 20:49 UTC, merged